spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testcruddb
    username: root
    password: Alexp896!
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: Alexp896!
  jpa:
    database: h2
  h2:
    console:
      enabled: true
