spring:
  datasource:
    url: jdbc:h2:mem:test
    username: test
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

fileRepositoryFolder: C:\\Users\\backu\\Desktop\\FileRepository
